apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
    annotations:
        policies.kyverno.io/category: Pod Security
        policies.kyverno.io/description: This policy ensures that any namespace specified in the source.namespace field of an AuthorizationPolicy's rules actually exists in the cluster.
        policies.kyverno.io/severity: medium
        policies.kyverno.io/subject: AuthorizationPolicy, Namespace
        policies.kyverno.io/title: Check AuthorizationPolicy Source Namespaces Exist
    name: check-authzpolicy-namespace-exists
spec:
    background: true
    rules:
        - context:
            - apiCall:
                jmesPath: items[].metadata.name
                urlPath: /api/v1/namespaces
              name: namespaces
          match:
            any:
                - resources:
                    kinds:
                        - AuthorizationPolicy
          name: validate-source-namespaces
          validate:
            foreach:
                - deny:
                    conditions:
                        all:
                            - key: '{{ element }}'
                              operator: AnyNotIn
                              value: '{{ namespaces }}'
                  list: request.object.spec.rules[].from[].source.namespaces[]
            message: The namespace(s) specified in the source namespaces field must exist in the cluster.
    validationFailureAction: Enforce