apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
    annotations:
        policies.kyverno.io/category: Security
        policies.kyverno.io/description: This policy ensures that the app specified in Telemetry's selector exists as a Pod in the cluster.
        policies.kyverno.io/severity: medium
        policies.kyverno.io/title: Validate Telemetry App Exists
    name: validate-telemetry-app-exists
spec:
    background: true
    rules:
        - context:
            - apiCall:
                jmesPath: items[?metadata.labels.app=='{{request.object.spec.selector.matchLabels.app}}'] | length(@)
                urlPath: /api/v1/namespaces/{{request.namespace}}/pods
              name: pods
          match:
            any:
                - resources:
                    kinds:
                        - Telemetry
          name: check-app-exists
          validate:
            deny:
                conditions:
                    all:
                        - key: '{{ pods }}'
                          operator: Equals
                          value: 0
          message: The app '{{request.object.spec.selector.matchLabels.app}}' specified in Telemetry selector must exist as a Pod in the cluster
    validationFailureAction: Enforce